### PR TITLE
Add SQL query recording.

### PR DESCRIPTION
**Pull request by bigplants**
Issue #19 

# Description of changes:
I added SQL queries into `SQL` tab as `Sanitized query`.
Like this:
screenshot_2019_02_14_12_31

Is this approach correct?
Please let me know if you have any suggestions.

### CODE REVIEW

**Comment by haotianw465** [comment]
Thank you for your contribution. Queries may contain sensitive data so the SDK takes caution on capturing any actual query. We have a difference review process of such feature which normally takes a little bit longer than the normal PRs. Would you mind adding some unit test against no sensitive data is captured?

**Comment by bigplants** [comment]
@haotianw465 Thanks for your reply.
It's exactly as you said, queries contain sensitive data in my changes.
But, actually, that is even better for an our application..

OK. I will try to masking sensitive data and adding unit test for that.

**Comment by shamdsc** [comment]
I'm very interested in this feature.  Is there any way for me to use it without building the gem myself off this branch?

**Comment by haotianw465** [comment]
@shamdsc You can subclass the X-Ray provided active record handler and override the transaction recording logic so the actual sql query is also added. 

We also have a backlog on recording parameterized queries but there is no ETA yet.

**Comment by shengxil** [comment]
For security concern, we are working on a feature to allow recording the SQL query with user provided sanitizer, as an opt-in feature across all languages. Closing this PR.

**Comment by rubenfonseca** [comment]
Hi, did you ever added support for recording SQL queries on the SDK?

**Pull request closed without merging**
