### PR TITLE
fix wrong number of arguments when calling to_json

### PR DESCRIPTION
**Pull request by somic**
*Issue #, if available:*

N/A

*Description of changes:*

Fix `wrong number of arguments (given 1, expected 0)` from inside MultiJson when calling `end_segment`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by haotianw465** [comment]
Sorry for the late reply. Do you have a simple repro code? What is the Ruby version you are running on? It's surprising that multi_json passes any argument on X-Ray data serialization.

**Comment by somic** [comment]
`Runtime: ruby2.5`

I can't provide a full repro but exception was coming from `XRay.recorder.end_segment` when it was trying to send it.

**Comment by somic** [comment]
Here is a repro - https://gist.github.com/somic/987cc079fc4d0d74f0c2bdab079dc3a4

**Comment by somic** [comment]
Thoughts? I don't mind if this PR is discarded and another, more elegant or more proper fix is implemented instead. My goal however is for it to work, without `wrong number of arguments` exceptions.

**Comment by awssandra** [comment]
Hi Somic, very sorry we punted on this. I'll get this prioritized.

**Comment by srprash** [comment]
Hi @somic . I tried the repro code that you posted in a lambda environment. It seems to be working fine with no exceptions. 
Also, looking into the code, we never call the [`entity.to_json`](https://github.com/aws/aws-xray-sdk-ruby/blob/1869ca5b72dfb206e42ef92d40a7fd2f4b53f465/lib/aws-xray-sdk/emitter/default_emitter.rb#L27) method with an argument.

Can you test the repro code with the latest version of the SDK? If you still get the issue, please let me know what arguments are being passed to the `to_json` method so we can dig deeper.

Thanks.

**Pull request closed without merging**
