### PR TITLE
Add Rails 6.1 ActiveRecord support

### PR DESCRIPTION
**Pull request by johan-smits**
*Issue #, if available:* #56

*Description of changes:* Support ActiveRecord 6.1

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]
Thanks a lot @johan-smits! This change looks fine to me - I noticed we don't seem to have any tests for rails :( Would adding a test that uses rails 6.1 be something you can help us with? If not no worries and we'll merge this

**Comment by johan-smits** [comment]
@anuraaga I did not find any tests for ActiveRecord thats why I did not add one. If you can point me out where they are I'm happy to add a new one.

**Comment by anuraaga** [comment]
Right :) That's the same conclusion I came to when looking through this repo for the first time. So it would start from adding rails as a dev dependency in the gemspec.

You don't have to do it of course :) Our team unfortunately doesn't have anyone super familiar with rails right now so we really appreciate the help from the community here - if you could add the dependency and a test using it similar to what we have in `test`, it would be really awesome. If not, it's also still awesome to have this PR so no worries.

**Comment by johan-smits** [comment]
@anuraaga not sure on how to make a test for this, I'm familiar with ActiveRecord but not so much on the testing area. Since it this code https://github.com/aws/aws-xray-sdk-ruby/blob/d5de6c21e83d7d250182273006c70bbf76962e4c/lib/aws-xray-sdk/facets/rails/active_record.rb#L10-L13 also only works with MySQL and PG, so this should also be setup to test this change.

**Comment by anuraaga** [comment]
@johan-smits No worries let's merge this in :) Thanks!

**Comment by johan-smits** [comment]
@anuraaga thanks, when would this get released?

**Pull request merged**
